name: Build & Run
run-name: ${{ github.actor }}'s build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Install TSC
        run: npm install tsc -g
      - name: Install Modules
        run: npm install --save-dev
      - name: Build
        run: npm run build
      
